language: node_js
sudo: required
node_js:
- lts/*
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 47.105.40.207
before_install:
- openssl aes-256-cbc -K $encrypted_be94fd40f0c4_key -iv $encrypted_be94fd40f0c4_iv
  -in deploy.sh.enc -out deploy.sh -d
- chmod u+x *.sh
script:
- sh ./deploy.sh
branch: master
env:
    global:
        - GH_REF: github.com/Thawsoar/vue-cms.git